<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
$config['pagination']['per_page'] = 100;
$config['num_links'] = 1;
$config['pagination']['page_query_string'] = TRUE;
$config['pagination']['full_tag_open'] = '<ul class="pagination justify-content-end">';
$config['pagination']['full_tag_close'] = '</ul>';
$config['pagination']['first_tag_open'] = '<li class="page-item">';
$config['pagination']['first_tag_close'] = '</li>';
$config['pagination']['first_link'] = 'First';
$config['pagination']['last_link'] = 'Last';
$config['pagination']['last_tag_open'] = '<li class="page-item">';
$config['pagination']['last_tag_close'] = '</li>';
$config['pagination']['next_link'] = '<i class="i i-arrow_forward_ios"></i>';
$config['pagination']['next_tag_open'] = '<li class="page-item">';
$config['pagination']['next_tag_close'] = '</li>';
$config['pagination']['prev_link'] = '<i class="i i-arrow_back_ios"></i>';
$config['pagination']['prev_tag_open'] = '<li class="page-item">';
$config['pagination']['prev_tag_close'] = '</li>';
$config['pagination']['cur_tag_open'] = '<li class="page-item disabled"><a class="page-link" href="#">';
$config['pagination']['cur_tag_close'] = '</a></li>';
$config['pagination']['num_tag_open'] = '<li class="page-item">';
$config['pagination']['num_tag_close'] = '</li>';
$config['attributes'] = array('class' => 'page-link');
